version: '3.2'
services:
  sut:
    image: opositatest/php-fpm:7.4
    volumes:
      - ./test/index.php:/var/www/html/web/index.php
    environment:
      - APP_ENV=${APP_ENV}
    container_name: php
    depends_on:
      - nginx

  nginx:
    build: .
    volumes:
      - ./test/index.php:/var/www/html/web/index.php
      - ./test/test.sh:/tmp/test.sh
    environment:
      - APP_ENV=${APP_ENV}
    command: bash -x /tmp/test.sh