version: '3.2'
services:
  php:
    image: opositatest/php-fpm
    volumes:
      - ./test/index.php:/var/www/html/public/index.php
      - php_unix_socket:/run/php/
    environment:
      - APP_ENV=${APP_ENV}

  sut:
    build: .
    volumes:
      - ./test/index.php:/var/www/html/public/index.php
      - ./test/test.sh:/tmp/test.sh
      - php_unix_socket:/run/php/
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - php
    command: bash -x /tmp/test.sh
volumes:
  php_unix_socket: