version: '3.2'
services:
  php:
    image: opositatest/php-fpm:7.4
    volumes:
      - ./test/index.php:/var/www/html/public/index.php
    environment:
      - APP_ENV=${APP_ENV}

  sut:
    build: .
    volumes:
      - ./test/index.php:/var/www/html/public/index.php
      - ./test/test.sh:/tmp/test.sh
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - php
    command: bash -x /tmp/test.sh