name: CICD
on:
  push:
    tags: [ '*' ]
    branches: [ "main" ]
  workflow_dispatch:
env:
      DOCKERHUB_REPOSITORY: opositatest/nginx
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
    
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
  
    - name: Build
      run: docker-compose -f docker-compose.test.yml build
    - name: Run test
      run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    - name: Get the version
      if: github.event_name == 'tags'
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

    - uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr

    - name: Build, tag and push image to Dockerhub and ECR - Tag
      if: github.event_name == 'tags'
      env:
        VERSION: ${{ steps.get_version.outputs.version }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t ${DOCKERHUB_REPOSITORY}:${VERSION} .
        docker tag ${DOCKERHUB_REPOSITORY}:${VERSION} ${ECR_REGISTRY}/${ECR_REPOSITORY}:${VERSION}
        docker push ${DOCKERHUB_REPOSITORY}:${VERSION}
        docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${VERSION}
    
    - name: Build, tag and push image to Dockerhub and ECR - latest
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t ${DOCKERHUB_REPOSITORY}:latest .
        docker tag ${DOCKERHUB_REPOSITORY}:latest ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
        docker push ${DOCKERHUB_REPOSITORY}:latest
        docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest